name: Demo build docker hub image

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  IMAGE_NAME: demo-app

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
      version: ${{ steps.push_step.outputs.version }}

    steps:
      - name: Checkout
        id: checkout_step
        uses: actions/checkout@v2

      - name: Build image
        id: build_step
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
          echo "Result of checkout_step was '${{ steps.checkout_step.outcome }}'"
          echo "::set-output name=build_id::${GITHUB_RUN_ID}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push image
        id: push_step
        run: |
          IMAGE_ID=${{ secrets.DOCKER_USER }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$GITHUB_RUN_ID

          # Set version fo output2
          echo "Image version: ${VERSION}"
          echo "::set-output name=version::${VERSION}"
